name=ESP Async WebServer
includes=ESPAsyncWebServer.h
version=3.9.3-beta
author=macc-n
maintainer=macc-n
sentence=Asynchronous HTTP and WebSocket Server Library for ESP32, ESP8266 and RP2040
paragraph=Supports: WebSocket, SSE, Authentication, Arduino Json 7, File Upload, Static File serving, URL Rewrite, URL Redirect, etc
category=Other
url=https://github.com/macc-n/ESPAsyncWebServer
architectures=*
license=LGPL-3.0
